version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: 'circleci/node:12.4'
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Build Project
          command: npm run build --prod
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token="$FIREBASE_TOKEN"
