version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:11-browsers'
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: "Install dependencies"
          command: 'npm install'
      - save_cache:
          paths:
            - node_modules
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: 'Build Project'
          command: 'npm run build'
      - run:
          name: "Run unit-tests"
          command: "npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI"
      - run:
          name: 'Deploy to Firebase Hosting'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
